#!/usr/bin/env tcsh

# MUST BE RUN FROM nunki.usc.edu, OTHERWISE IT DOESN'T KNOW
#   WHERE TO FIND THE NEEDED TEST FILES

set srcdir=~csci531/public/cs531/hw2

# Boilerplate constants
set p0="yesnomaybe"
set p1="cs531-f09"
set p2="vcrypto"
set p3="password"
set p4="emptyString"
set p5="applied"
set p6="cryptography"
set p7="publickey"

set len0=320
set len1=241
set len2=202
set len3=803
set len4=724

#
# small.pbm: +5 points
#
/bin/rm bar*.pbm

./hw2 encrypt -p="$p0" -out=bar $srcdir/small.pbm
./hw2 merge bar.1.pbm bar.2.pbm > bar-merged.pbm
./hw2 decrypt bar-merged.pbm > bar.pbm

echo "==> $srcdir/small.pbm "
diff $srcdir/small.pbm bar.pbm

#
# hello.pbm: +5 points
#
/bin/rm bar*.pbm

cat $srcdir/hello.pbm | ./hw2 encrypt -p="$p1" -out=bar
./hw2 merge bar.1.pbm bar.2.pbm | ./hw2 decrypt > bar.pbm

echo "==> $srcdir/hello.pbm "
diff $srcdir/hello.pbm bar.pbm

#
# bowtie.pbm: +5 points
#
/bin/rm bar*.pbm

cat $srcdir/bowtie.pbm | ./hw2 encrypt -p="$p2" -out=bar
./hw2 merge bar.1.pbm bar.2.pbm | ./hw2 decrypt > bar.pbm

echo "==> $srcdir/bowtie.pbm "
diff $srcdir/bowtie.pbm bar.pbm

