#!/usr/bin/env tcsh

# MUST BE RUN FROM nunki.usc.edu, OTHERWISE IT DOESN'T KNOW
#   WHERE TO FIND THE NEEDED TEST FILES

set srcdir=~csci531/public/cs531/hw4

# Boilerplate constants
set len1=11
set len2=37
set len3=23
set len4=54
set len5=7
set len6=101
set len7=193

#
# keygen (+7 points)
# Note: output will be inspected if they look "random" enough
#
/bin/rm -f x?.keys

./hw4 keygen -t=$len1 > x1.keys
./hw4 keygen -t=$len2 > x2.keys
./hw4 keygen -t=$len3 > x3.keys
./hw4 keygen -t=$len4 > x4.keys
./hw4 keygen -t=$len5 > x5.keys
./hw4 keygen -t=$len6 > x6.keys
./hw4 keygen -t=$len7 > x7.keys

foreach f (1 2 3 4 5 6 7)
	echo "==> checking x$f.keys"
	$srcdir/checkKeys x$f.keys
end
