#!/usr/bin/env tcsh

# MUST BE RUN FROM nunki.usc.edu, OTHERWISE IT DOESN'T KNOW
#   WHERE TO FIND THE NEEDED TEST FILES

set srcdir=~csci531/public/cs531/hw4

# Boilerplate constants
set len1=11
set len2=37
set len3=23
set len4=54
set len5=7
set len6=101
set len7=193

#
# crypt (+10 points, +2 for each correct answer)
#
/bin/rm -f f?.ct
foreach f (1 2 3 4 5)
	./hw4 crypt -k=$srcdir/f$f.keys $srcdir/f$f.pt > f$f.ct
	echo "==> $srcdir/f$f.ct"
	diff f$f.ct $srcdir/f$f.ct
end

#
# decrypt (+10 points, +2 for each correct answer)
#
/bin/rm -f f?.pt
foreach f (1 2 3 4 5)
	cat $srcdir/f$f.ct | ./hw4 crypt -k=$srcdir/f$f.invkeys > f$f.pt
	echo "==> $srcdir/f$f.pt"
	diff f$f.pt $srcdir/f$f.pt
end
