#!/usr/bin/env tcsh

# MUST BE RUN FROM nunki.usc.edu, OTHERWISE IT DOESN'T KNOW
#   WHERE TO FIND THE NEEDED TEST FILES

set srcdir=~csci531/public/cs531/hw4

# Boilerplate constants
set len1=11
set len2=37
set len3=23
set len4=54
set len5=7
set len6=101
set len7=193

#
# inverse key (+5 points, +1 points for each correct case)
#

set srcdir=~csci531/public/cs531/hw4
/bin/rm -f f?.invkeys
foreach f (1 2 3 4 5)
	./hw4 invkey $srcdir/f$f.keys > f$f.invkeys
	echo "==> $srcdir/f$f.invkeys"
	diff f$f.invkeys $srcdir/f$f.invkeys
end
