#!/usr/bin/env tcsh

# MUST BE RUN FROM nunki.usc.edu, OTHERWISE IT DOESN'T KNOW
#   WHERE TO FIND THE NEEDED TEST FILES

set srcdir=~csci531/public/cs531/hw4

# Boilerplate constants
set len1=11
set len2=37
set len3=23
set len4=54
set len5=7
set len6=101
set len7=193

#
# solve (+15 points, +3 for each correct answer, +1 for each method)
#
# Note: For the floating values (IC and E(IC) in f?.solve, the numbers
#       do not have to match exactly; they just have to be close.
#

/bin/rm -f f?.solve

./hw4 solve -l=17 $srcdir/f1.ct > f1.solve
./hw4 solve -l=20 $srcdir/f2.ct > f2.solve
./hw4 solve -l=9  $srcdir/f3.ct > f3.solve
./hw4 solve -l=11 $srcdir/f4.ct > f4.solve
./hw4 solve -l=16 $srcdir/f5.ct > f5.solve

foreach f (1 2 3 4 5)
	echo "==> $srcdir/f$f.solve"
	diff f$f.solve $srcdir/f$f.solve
end


