#!/usr/bin/env tcsh

# MUST BE RUN FROM nunki.usc.edu, OTHERWISE IT DOESN'T KNOW
#   WHERE TO FIND THE NEEDED TEST FILES

set srcdir=~csci531/public/cs531/hw4

# Boilerplate constants
set len1=11
set len2=37
set len3=23
set len4=54
set len5=7
set len6=101
set len7=193

#
# crypt, then decrypt using student's keygen code (+10 points, +2 for each correct answer)
#
/bin/rm -f f?.pt f?.ct f?.keys f?.invkeys

./hw4 keygen -t=3 > f1.keys
./hw4 keygen -t=7 > f2.keys
./hw4 keygen -t=8 > f3.keys
./hw4 keygen -t=2 > f4.keys
./hw4 keygen -t=4 > f5.keys

foreach f (1 2 3 4 5)
	./hw4 invkey f$f.keys > f$f.invkeys
	cat $srcdir/f$f.pt | ./hw4 crypt -k=f$f.keys > f$f.ct
	
	./hw4 crypt -k=f$f.invkeys f$f.ct > f$f.pt
	echo "==> $srcdir/f$f.pt"
	diff f$f.pt $srcdir/f$f.pt
end
