#!/usr/bin/env tcsh

# MUST BE RUN FROM nunki.usc.edu, OTHERWISE IT DOESN'T KNOW
#   WHERE TO FIND THE NEEDED TEST FILES

set srcdir=~csci531/public/cs531/hw7

# Boilerplate constants
set k0=15                 
set k1=18
set k2=21
set k3=24
set k4=27
set k5=30
set k6=33
set k7=36
set k8=39
set k9=42
set k10=45

#
# (E) maurer (+22 points, +2 for each correct answer)
#
/bin/rm -f f?.ma f??.ma

set pf=$srcdir/primes.n223
set rf=$srcdir/rnd.220

./hw7 maurer -k=$k0 -p=$pf -r=$rf > f0.ma
./hw7 maurer -k=$k1 -p=$pf -r=$rf > f1.ma
./hw7 maurer -k=$k2 -p=$pf -r=$rf > f2.ma
./hw7 maurer -k=$k3 -p=$pf -r=$rf > f3.ma
./hw7 maurer -k=$k4 -p=$pf -r=$rf > f4.ma
./hw7 maurer -k=$k5 -p=$pf -r=$rf > f5.ma
./hw7 maurer -k=$k6 -p=$pf -r=$rf > f6.ma
./hw7 maurer -k=$k7 -p=$pf -r=$rf > f7.ma
./hw7 maurer -k=$k8 -p=$pf -r=$rf > f8.ma
./hw7 maurer -k=$k9 -p=$pf -r=$rf > f9.ma
./hw7 maurer -k=$k10 -p=$pf -r=$rf > f10.ma

foreach f (0 1 2 3 4 5 6 7 8 9 10)
	echo "==> $srcdir/f$f.ma"
	diff f$f.ma $srcdir/f$f.ma
end

/bin/rm -f f?.ma f??.ma
