#!/usr/bin/env tcsh

# MUST BE RUN FROM nunki.usc.edu, OTHERWISE IT DOESN'T KNOW
#   WHERE TO FIND THE NEEDED TEST FILES

set srcdir=~csci531/public/cs531/hw5

# Boilerplate constants
set key=0123456789abcdef

#
# 4. decrypt (+10 points, +1 for each correct answer)
/bin/rm -f fout.? ferr.?
#
# use various tablefile to decrypt
#
foreach f (0 1 2 3 4 5 6 7 8 9)
	(./hw5 decrypt -k=$key -t=$srcdir/f$f $srcdir/f22.$f.enc > fout.$f) >& ferr.$f
	echo "==> fout.$f"
	diff fout.$f $srcdir/f24
	echo "==> $srcdir/f24.$f.err"
	diff ferr.$f $srcdir/f24.$f.err
end
/bin/rm -f fout.? ferr.?

#
# 5. decrypt from stdin (+10 points, +1 for each correct answer)
#

#
# use various tablefile to decrypt from stdin
#
foreach f (0 1 2 3 4 5 6 7 8 9)
	cat $srcdir/f22.$f.enc | (./hw5 decrypt -k=$key -t=$srcdir/f$f > fout.$f) >& ferr.$f
	echo "==> fout.$f"
	diff fout.$f $srcdir/f24
	echo "==> $srcdir/f24.$f.err"
	diff ferr.$f $srcdir/f24.$f.err
end
/bin/rm -f fout.? ferr.?

