#!/usr/bin/env tcsh

# MUST BE RUN FROM nunki.usc.edu, OTHERWISE IT DOESN'T KNOW
#   WHERE TO FIND THE NEEDED TEST FILES

set srcdir=~csci531/public/cs531/hw6

# Boilerplate constants

#
# (A) tablecheck (+9 points, +1 points for each correct case)
# Note: should generate no output
#

foreach f (0 1 2 3 4 5 6 7 8)
	echo "==> $srcdir/f$f.tbl"
	./hw6 tablecheck -t=$srcdir/f$f.tbl
end
